### PR TITLE
Add testing page

### PR DESCRIPTION
**Pull request by mingyli**
`bundle exec jekyll serve --draft`

### CODE REVIEW

**Comment by mluogh** [comment]
Good idea!

Some concerns:

Should the welcome to Jekyll be here?

image

Also note how my article appears on top of the Testing. In the future as we add more articles we will have to scroll down many articles to see testing page. I think this can be solved if we put the date of testing MD as far in the future as possible (i.e. Dec 31st 9999)

image

**Comment by mingyli** [comment]
Thank you for bringing those points to my attention!
 
1. The Welcome to Jekyll should be there, as it was previously in `_drafts_
2. Good point. Removing the `date` field in the front matter allows drafts to always appear at the top. I have committed this change

**Comment by mluogh** [comment]
1. Is there any point to having the Welcome to Jekyll draft? I believe all it does it clutter up our code. Might we remove it?

2. Thank you. Good work.

**Comment by mingyli** [comment]
1. Maybe in a future pr! Ha-hA. I think we can remove it in the future if you feel strongly about it

**Review by mluogh — APPROVED** [review]
Approved.

**Pull request merged**
